name: flutter_app_bloc_architecure
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Compare Class Object Easily
  equatable: ^2.0.0
  #Dart Functional Programming
  dartz: ^0.9.2
  #Check Internet Connectivity
  data_connection_checker: ^0.3.4
  #State Management Lib
  flutter_bloc: ^7.0.0
  #Dependacies Injection
  get_it: ^6.1.1
  #Http Network Lib
  dio: ^4.0.0
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

 
 
 
 

 
 

 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
